name: lib
description: Eventos de sua cidade em um só lugar.

version: 1.0.17+18

environment:
  sdk: ">=2.18.1 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3
  http_parser: ^4.0.0
  url_launcher: 6.1.10
  font_awesome_flutter: ^10.1.0
  share: ^2.0.4
  introduction_screen: ^2.1.0
  shared_preferences: ^2.0.7
  intl: ^0.17.0
  cupertino_icons: ^1.0.2
  flutter_modular: ^5.0.3
  flutter_bloc: ^7.0.1
  bloc: ^7.0.0
  dio: ^4.0.1
  rx_notifier: ^1.1.0  
  google_fonts: ^2.1.0
  cached_network_image: ^3.1.0+1
  map_launcher: ^2.1.1 
  geolocator: ^9.0.2
  flutter_widget_from_html_core: ^0.8.2
  connectivity_plus: ^2.1.0
  flutter_launcher_icons: ^0.11.0
  localization: ^1.1.0
  flutter_triple: ^1.2.5
  flutter_blurhash: ^0.6.0
  dartz: ^0.10.1
  carousel_slider: ^4.1.1
  permission_handler: any
  screenshot: ^1.3.0
  path_provider: ^2.0.2
  skeletons: ^0.0.3
  flutter_image: ^4.1.6
  story: ^0.6.0
  asuka: ^2.0.1+3
  firebase_core: ^2.8.0
  new_version_plus: ^0.0.9
  package_info_plus: ^3.1.2
  



dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: false
  ios: true
  image_path: "images/app_icon.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  assets:
    - images/

  fonts:
    - family: LEMONMILK
      fonts:
        - asset: fonts/LEMONMILK-Medium.otf
          weight: 200
